// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android =FirebaseOptions(
    apiKey: 'AIzaSyD6iBuJCYlB3t_NTp0441G2-DR3Q_6oLys',
    appId: '1:67412645959:android:94f614a9d912ba799ff962',
    messagingSenderId: '67412645959',
    projectId: 'weather-app-flutter-dd43f',
    storageBucket: 'weather-app-flutter-dd43f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAum-3dB7C92t5zuPolIaRue6PDn79eIk',
    appId: '1:67412645959:ios:d222b021ba48ad399ff962',
    messagingSenderId: '67412645959',
    projectId: 'weather-app-flutter-dd43f',
    storageBucket: 'weather-app-flutter-dd43f.appspot.com',
    iosBundleId: 'com.example.weatherAppFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAum-3dB7C92t5zuPolIaRue6PDn79eIk',
    appId: '1:67412645959:ios:43618c6c6f82f68a9ff962',
    messagingSenderId: '67412645959',
    projectId: 'weather-app-flutter-dd43f',
    storageBucket: 'weather-app-flutter-dd43f.appspot.com',
    iosBundleId: 'com.example.weatherAppFlutter.RunnerTests',
  );
}
